Added missing ol7_developer_EPEL repo for "Oracle Linux"
Otherwise on "Oracle Linux" during "yum install pgadmin4-web" I get:

Error: Package: pgadmin4-python-flask-principal-0.4.0-14.rhel7.1.noarch (pgdg10)
Requires: python-flask
Error: Package: pgadmin4-python-flask-principal-0.4.0-14.rhel7.1.noarch (pgdg10)
Requires: python-blinker